artifact_location: file:///c:/Users/aziz/Desktop/kidney_disease_classification/Kidney-Disease-Classification/TRACKING_URI/0
creation_time: 1715009975971
experiment_id: '0'
last_update_time: 1715009975971
lifecycle_stage: active
name: Default
